FROM art-dash-server:base


# This build is meant to be based on an existing build and
# update just doozer, elliott, and art-bot.

# use same non-root user from the initial install
ARG USERNAME=dev
# On Linux, replace with your actual UID, GID if not the default 1000
ARG USER_UID=1000
ARG USER_GID=$USER_UID

USER "$USER_UID"
CMD ["python3", "manage.py", "makemigrations"]
CMD ["python3", "manage.py", "migrate"]