apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: art-dash-server
    name: art-dash-server-base
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: art-dash-server:base
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/openshift-eng/art-dashboard-server
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
        dockerfilePath: Dockerfile.base
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
      - imageChange:
          lastTriggeredImageID: null
        type: ImageChange
      - type: ConfigChange